### ISSUE TITLE
Security Lab

### ISSUE THREAD

**Issue by giorgio-sonra** [giorgio-sonra/SEBC#6]
Problem with TLS authentication between CM agents and server

`agentServer-0:org.mortbay.log: javax.net.ssl.SSLHandshakeException: null cert chain`

**Comment by giorgio-sonra** [comment]
I've tried to got until TLS level 3... In case I don't the same CA for all machines and the self-signed keys weren't recognized in the server.

**Comment by mfernest** [comment]
This amount of work for the task is impressive.

Complete
